package com.pd.beertimer.util

const val CHANNEL_ID = "BEER_TIME_APP_CHANNEL"
const val SHARED_PREF_DRINKING_TIMES = "SHARED_PREF_DRINKING_TIMES"
const val SHARED_PREF_DRINKING_CALCULATOR = "SHARED_PREF_DRINKING_CALCULATOR"
const val SHARED_PREF_FIRST_TIME_LAUNCH = "SHARED_PREF_FIRST_TIME_LAUNCH"
const val SHARED_PREF_ROOM_INIT = "SHARED_PREF_ROOM_INIT"
const val SHARED_PREF_BEER_TIME = "BT_BESTE_APP_DA"
const val SHARED_PREF_USES_LITERS = "SHARED_PREF_USES_LITERS"

const val NOTIFICATION_ID = 1337
